adding a check to see if hotelOwner is changing its hotel
pdybowski/booking-clone-Api pull request #107
Opened 2021-03-09 14:08 UTC by ibednorz

2021-03-09 16:28 UTC, pdybowski reviewed
Did you test it?

2021-03-09 16:28 UTC, pdybowski commented on services/ownerService.js
> +exports.updateHotel = async (id, data, req) => {
Do these params matches arguments that are passed when we call this function? I mean here we have req and where we call this function we pass req.user._id

2021-03-09 16:28 UTC, pdybowski commented on services/ownerService.js
> +  if (!isObjIdEqualToMongoId(req.user._id, reservation.hotel)) {
What is reservation? We didn't declare it lol

2021-03-11 10:59 UTC, pdybowski commented
still waiting for fixes

2021-03-11 19:28 UTC, pdybowski requested changes
Nie No zle. Masz zmienna która nie jest nigdzie zdefiniowana. Sprawdzasz czy hotel istnieje później niż sprawdzasz czy należy do hotel ownera. Ten kod nie zadziała jak powinien...

2021-03-11 19:28 UTC, pdybowski commented on services/ownerService.js
> +  if (!isObjIdEqualToMongoId(userId, hotel.ownerId)) {
First we must check if hotel exists. Then if it belongs to the owner..

2021-03-11 19:28 UTC, pdybowski commented on services/ownerService.js
> +  let hotel = await Hotel.findById(id)
Check something like findOneAndUpdate. You should be able to check if hotel exists and belongs to the hotel owner.

2021-03-12 14:38 UTC, bartoszbialecki commented on controllers/ownerController.js
> +    if (error instanceof mongoose.Error.CastError) {
here should be only next(error) like I changed earlier

2021-03-12 14:38 UTC, bartoszbialecki commented on services/ownerService.js
> +    throw new ApiError(403, 'Forbidden')
should be used ForbiddenError class

2021-03-12 15:23 UTC, bartoszbialecki approved these changes
Are you merged all current changes? Everything works?

2021-03-12 16:08 UTC, merged