API all - admin
pdybowski/booking-clone-Api pull request #47
Opened 2021-02-25 16:13 UTC by ibednorz

2021-02-25 16:34 UTC, GoraJakub requested changes
Please redo all errors

2021-02-25 16:34 UTC, GoraJakub commented on routes/admin.js
> +        res.status(500).send('Something went wrong')
Could you change errors to 'throw new ApiError(code,message)'?

2021-02-25 20:08 UTC, bartoszbialecki commented on routes/admin.js
> +        { "role": /hotelOwner/i }
hotelOwner should not be used like this, we have roles.js in models directory so use it

2021-02-25 20:10 UTC, bartoszbialecki commented on routes/admin.js
> +        const id = await User.find({ email: email, "role": /hotelOwner/i }, '_id')
I think you can find and delete in one query

2021-02-25 20:11 UTC, bartoszbialecki reviewed
The same comment as in Kuba's PR, I think we should use everywhere json, so try res.json instead of res.send.
Your endpoints are not protected, everyone can call them, not only admin user

2021-02-26 11:16 UTC, pdybowski commented on routes/admin.js
> +        res.status(500).send('Something went wrong')
Send ({ message: 'something went wrong' }) 
Or use .json 
Whatever

2021-02-26 17:17 UTC, pdybowski commented on routes/admin.js
> +    const id = await User.findOneAndDelete({
check and fix

2021-02-26 17:17 UTC, pdybowski commented on routes/admin.js
> +router.put('/owner/accept/:email', isAdmin, async (req, res) => {
move isAdmin middleware to startu/routes

2021-02-26 18:56 UTC, merged